#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import py
from git import Repo
from jinja2 import Environment, PackageLoader, select_autoescape


if __name__ == '__main__':
    repo_path = py.path.local(os.getcwd()) / 'salt-packaging'
    repo = Repo(repo_path.strpath)

    existing_patches = set(
        [py.path.local(it.path).basename for it in repo.commit('HEAD~1').tree['salt'] if it.path.endswith(".patch")]
    )

    current_patches = set(
        [py.path.local(it.path).basename for it in repo.commit('HEAD').tree['salt'] if it.path.endswith(".patch")]
    )

    deleted = existing_patches.difference(current_patches)
    added = current_patches.difference(existing_patches)
    modified = set(
        [py.path.local(it.a_path).basename for it in repo.commit("HEAD").diff("HEAD~1") if it.a_path.endswith(".patch")]
    ).difference(added.union(deleted))


    env = Environment(
        loader=PackageLoader('updatechangelog', 'templates'),
        autoescape=select_autoescape(['html'])
    )

    template = Template("""

    """)
    import pdb; pdb.set_trace()
